version: '3'

services: 
  db: 
    image: mysql
    container_name: 'mysql04'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=tzb850112
      - MYSQL_USER=tanzb
      - MYSQL_PASSWORD=tzb850112
    volumes: 
      - /F/Docker/mysql/mysql-init:/docker-entrypoint-initdb.d
  web:
    build: .
    container_name: 'aspnetcore04'
    ports:
      - '8003:80'
    depends_on:
      - db

